### ISSUE TITLE
Run suite with multiple data set

### ISSUE THREAD

**Issue by AshwinK1989** [intuit/automation-for-humans#36]
Hi Team,
Is there any way to run a single suite with different data set like Cucumber have **Examples** keyword.?

**Comment by MadaraUchiha-314** [comment]
@AshwinK1989 Currently we don't have such a capability. I am thinking how it aligns with the [core-philosophy](https://github.com/intuit/automation-for-humans#core-philosophy) of [automation-for-humans](https://github.com/intuit/automation-for-humans) wherein the test cases should be human readable and in future parsable by a NL parser instead of a keyword based parser that we currently have.
